language: java

jdk:
  - oraclejdk8

cache:
  directories:
   - $HOME/.gradle

before_install:
  - jdk_switcher use oraclejdk8
  - java -version

script:
  - ./gradlew clean check jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)